---

- name: Verify play
  hosts: all
  tasks:
    - name: Ensure nginx port is reachable
      wait_for:
        host: localhost
        port: 80
        timeout: 5

    - name: Ensure nginx_vts_exporter port is reachable
      wait_for:
        host: localhost
        port: 9913
        timeout: 5
